name: flutter_x_container
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  path_provider: ^2.1.1
  flutter_inappwebview: ^6.1.5
  archive: ^4.0.7
  shared_preferences: ^2.1.0
  file_picker: ^10.3.3
  xml: ^6.5.0
  http: ^1.5.0
  #dart_eval: ^0.8.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true